name: CI
on:
  push:
    branches:
    - '*'
  pull_request:
  schedule:
  - cron: 0 14 * * 0
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ^1
      id: go
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Make
      run: make ci
    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v2
    